### ISSUE TITLE
this before super in constructor

### ISSUE THREAD

**Issue by kitten** [philplckthun/react-compat-component#2]
As shown in the example: This implementation kind of demands the mixins array to be set in the constructor before the call to super. This might get solved by the introduction of property initialization to Babel or in ES7 (even ES6?).

One workaround would be to pass the mixins array to the super call. But it would definitely not be nice.

**Comment by RickWong** [comment]
> One workaround would be to pass the mixins array to the super call. But it would definitely not be nice.

Why not? Of course the component would then be tied to the interface of the super-constructor. But I don't think that's bad. It's tied either way, in the end.

``` js
  super(props, {
    mixins: [HelloMixin]
  });
```

**Comment by RickWong** [comment]
How about changing it to a method 'getMixins'? will that work in the super-constructor?

**Comment by kitten** [comment]
Changing it to a method is actually a very, VERY good idea. I didn't think of that. Thank you very much I'll implement it today 

I feel like passing it to super conflicts with some other usecases. For example of context. So I wanted to keep that clean.
