### ISSUE TITLE
Implement Autobind and getInitialState as mixins

### ISSUE THREAD

**Issue by RickWong** [philplckthun/react-compat-component#3]
Is this possible?

**Comment by kitten** [comment]
Yes it's possible. I could separate it out.
But why? What is to achieve from it?

**Comment by RickWong** [comment]
It would make this component more modular. But I guess you can classify these features as core.

**Comment by kitten** [comment]
I think it wouldn't make sense, as this module is trying to restore createClass functionality. Also the code isn't that complex after all.

**Comment by RickWong** [comment]
Agreed. Nice work on `propTypes` btw! :)

**Comment by kitten** [comment]
Thanks, but it's not working yet. I'm merging the mixins' into propTypes and defaultProps after calling super in the meta-constructor. So it's not actually using these values. I experimented with replicating the process before calling super, but it's impossible, given that I can't even call this before it. Kind of out of ideas.

**Comment by RickWong** [comment]
Related thread on StackOverflow: http://stackoverflow.com/a/22986568/217782
