### ISSUE TITLE
propTypes / getPropTypes evaluation

### ISSUE THREAD

**Issue by kitten** [philplckthun/react-compat-component#5]
At the time propTypes probably aren't evaluated anymore (remember me to introduce unit testing).

This is due to getPropTypes getting called after the meta-constructor's super call, which makes React evaluate the propTypes before they're even set.

**Comment by RickWong** [comment]
Related thread on StackOverflow: http://stackoverflow.com/a/22986568/217782

**Comment by RickWong** [comment]
Hey this seems to work with the default `React.Component`. At least it does with Babel.

``` js

class Foo extends React.Component {
    static get propTypes () {
        return {
            bar: React.PropTypes.number
        };
    }
    render () {
        return <p>Hello</p>;
    }
}

<Foo bar="string" />;
```

> Warning: Failed propType: Invalid prop `bar` of type `string` supplied to `Foo`, expected `number`. Check the render method of `Main`.

**Comment by kitten** [comment]
Thanks! I will try to build on that ;)

**Comment by kitten** [comment]
I couldn't inject anything useful through static methods. So either the user makes his propTypes and defaultProps function static which makes it impossible to mutate it to include the mixins values, and which is another change from the original createClass function, or the wrapper class reproduces the props check & merging functionality of the React.Component class.

In 1.2.0 it does the latter.

I'm not sure if it's optimal, but I'll look into it.
